services:
  web:
    build: ./php/.
    ports:
        #host:container port
      - "8010:80"
    volumes:
      - ./:/var/www/html
      - ./php/xdebug_log:/xdebug_logs
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      XDEBUG_MODE: develop,debug
      XDEBUG_CONFIG:
        client_host=host.docker.internal
        start_with_request=yes
    networks:
      network1:
        ipv4_address: 172.16.1.10

  #php:
   # build: docker/php-fpm/.
   # networks:
    #  network1:
     #   ipv4_address: 172.16.1.11
networks:
    network1:
        name: php-playground-network-driver
        ipam:
          driver: default
          config:
          - subnet: "172.16.1.0/24"